name = "nucleus"
compatibility_date = "2024-08-08"

[pages]
pages_build_output_dir = "client/dist"

[vars]
# Clerk
CLERK_PUBLISHABLE_KEY = "${VITE_CLERK_PUBLISHABLE_KEY}"
CLERK_SECRET_KEY = "${CLERK_SECRET_KEY}"

# App
FRONTEND_URL = "${FRONTEND_URL}"
